### ISSUE TITLE
[FEATURE]Explore - Show Redaction

### ISSUE THREAD

**Issue by wpaven** [marklogic-community/envision#102]
**Is your feature request related to a problem? Please describe.**

**What is the user-facing scenario that prompted this gap in functionality?**

For the user that logs in who is only allowed to see redacted docs, show the redacted record in the Explore detail pane.

Keep impact minimal to Envision, and reusable for any user configured properly in the server/hub

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by paxtonhare** [comment]
finished and in develop. waiting for 1.0.6 release
