### ISSUE TITLE
[BUG] Concepts lost if you change IRI on Entity

### ISSUE THREAD

**Issue by wpaven** [marklogic-community/envision#107]
*### Welcome Envision enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:

Change IRI on entity.  Any projected concepts will cease to be projected in Explore.
Paxton has more detail here.  Has to do with model.json and TDE generation for supporting concepts.

What behavior are you expecting?

What are the steps to reproduce the issue:
1)
2)
3)

#### Tech details

Which Operating System are you using?

Which version of MarkLogic are you using?

Which version of the Data Hub are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  `java -jar envision.jar -d > myoutput.txt`

**Comment by paxtonhare** [comment]
this was magically fixed at some point.
