### ISSUE TITLE
[FEATURE] Upload - add support for .xml and .json files

### ISSUE THREAD

**Issue by wpaven** [marklogic-community/envision#127]
**Is your feature request related to a problem? Please describe.**

**What is the user-facing scenario that prompted this gap in functionality?**

I want to be able to select a bunch of .json or .xml off the filesystem and load into the data hub

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by paxtonhare** [comment]
fixed in develop
