### ISSUE TITLE
[FEATURE] Integrate UX Improvement - Prompt for Flow

### ISSUE THREAD

**Issue by wpaven** [marklogic-community/envision#146]
**Is your feature request related to a problem? Please describe.**

**What is the user-facing scenario that prompted this gap in functionality?**

in a new hub with no flows, 
can click add step without creating flow, nothing happens
let's
  grey out add step and prompt to create a flow
  once flow created, then  ungrey out button for selected flow

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by paxtonhare** [comment]
fixed in PR
