### ISSUE TITLE
[BUG] Deleting a nested entity orphans properties

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/envision#161]
If I delete a nested entity and there are still properties pointing at it, those properties get orphaned and the system goes wonky.

**Comment by wpaven** [comment]
This occurs if you delete the entity circle on the canvas.  The workaround is to first delete the property from its reference in the detail pane for the entity it's embedded in.  Then actually delete the entity from the canvas.

Example.  
Create entity Address
Create entity Employee
Add property to Employee named 'homeAddress' of type Address.

To remove Address
1) Delete property Employee.homeAddress
2) Delete Address entity
