### ISSUE TITLE
[FEATURE] Collapsable Column Views

### ISSUE THREAD

**Issue by awanczowski** [marklogic-community/envision#195]
**Is your feature request related to a problem? Please describe.**
A small amount of screen real estate when mapping.

**What is the user-facing scenario that prompted this gap in functionality?**
Create a mapping step in the integrate view.

**Describe the solution you'd like**
As a user, I would like to collapse/hide the column "flows" and "manage my data" in the integrate view. This will give me more of a workspace for mappings and steps when working on a small screen.

**Comment by xmlnovelist** [comment]
This one's already done: you click the “database” icon on the right and on the left you click the manage flows button.
