### ISSUE TITLE
[BUG] Error saving model when no model loaded

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/envision#49]
Sounds like an oxymoron. But if you open envision and there are no models to load then it shows a blank graph. Try adding a node and it will start throwing 500 errors.

This is because there is no named model created and in scope.

The fix is to not allow new nodes until a current model is set.

**Comment by wpaven** [comment]
discussed with paxton, this happens with virgin hub with no models in database and models in /conceptConnectorModels.

**Comment by wpaven** [comment]
duplicate
