### ISSUE TITLE
[BUG] Envision installs DHF 5.1 components in a 5.2.1 DH

### ISSUE THREAD

**Issue by xmlnovelist** [marklogic-community/envision#50]
*### Welcome Envision enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:
Start with a DHF 5.2.1 project and Quickstart 5.2.1. 
Install envision jar into DHS 5.2.1 project folder.
Log in to envision. Observe “installing” message. 
Attempt to log in to DHF with Quickstart 5.2.1. 
Result is the “Data Hub is older than Quickstart” message. Scratch head. Follow update instructions even though the DHF 5.2.1 install was working correctly previous to Envision “installing” message. 

#### Tech details

Which Operating System are you using?
MacOS

Which version of MarkLogic are you using?
10.0-3

Which version of the Data Hub are you using?
5.2.1

**Comment by wpaven** [comment]
Use Envision with DHF 5.1 until this is fixed.
