### ISSUE TITLE
[BUG] Changing the id of an entity breaks its relationships to concepts

### ISSUE THREAD

**Issue by xmlnovelist** [marklogic-community/envision#53]
*### Welcome Envision enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Changing the property assigned to the id of an entity on the Connect screen breaks links to concepts; links to concept stop appearing on the Explore screen.

What behavior are you expecting?

Expecting any changes to model to be reflected in the explore view.

What are the steps to reproduce the issue:

Run Envision as a jar in the directory of a DHF project.

Create a model with an entity and 2 concepts. 
Run your DH flows. Ingest and harmonize.
Explore the DH on the Explore screen. Everything looks good.
Go to Connect screen.
Change your entity:
create a new property. Assign it to be the model's id.
Run Mapping in Quickstart to populate your new id property with unique values.
Go to Explore screen.
Your Entity no longer has any related Concepts.

(NOTE: opening relationships on entity pane and pressing SAVE on each relationship fixes this.)

#### Tech details

Which Operating System are you using?
mac os

Which version of MarkLogic are you using?
10.0-3 in Docker

Which version of the Data Hub are you using?
5.2.1

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  `java -jar envision.jar -d > myoutput.txt`

**Comment by xmlnovelist** [comment]
Calling out the workaround: opening relationships on entity pane and pressing SAVE on each relationship fixes this.

**Comment by paxtonhare** [comment]
@xmlnovelist can you retest this? I think it's OBE.

**Comment by paxtonhare** [comment]
@xmlnovelist nevermind. I verified it's still an issue.

**Comment by paxtonhare** [comment]
this was fixes by the latest PR
