### ISSUE TITLE
[FEATURE]Add support DateTime Support for property Type. 

### ISSUE THREAD

**Issue by bgeorge11** [marklogic-community/envision#55]
**Is your feature request related to a problem? Please describe.**
DateTime is not a supported data type in Envision. For adding such a data type, we need to go back to editing the entity definition file or QS. The dateTime added there shows in Envision as Date. and when model is edited in Envision for something else, the type gets overwritten. 

**What is the user-facing scenario that prompted this gap in functionality?**
Explained above

**Describe the solution you'd like**
Add dateTime as a supported data type. 

**Describe alternatives you've considered**
Explained above. 

**Additional context**

**Comment by wpaven** [comment]
1.0.5
