### ISSUE TITLE
[FEATURE] Can't expand Concepts in Explore view

### ISSUE THREAD

**Issue by xmlnovelist** [marklogic-community/envision#60]
*### Welcome Envision enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue
There is no UI for expanding Concepts in Explore view. You can only view the Concept and any Entities that use the Concept as an object. 
Whereas you can create links that have Concepts as subjects and view them in the Know tab.

What behavior are you expecting?
Expect to be able to click on a Concept in Explore view and see the Expand relationships UI.

What are the steps to reproduce the issue:
1)Create a Concept
2)Link an Entity to the concept so the relationship's from property is the Concept.
3)On Explore, try to view related Entities by clicking on the Concept to reveal its Expand Relationships UI.

Observe there is no Expand Relationships UI: there is no way to visualize a concept's related entities in Explore.

#### Tech details

Which Operating System are you using?
MacOS/ Firefox

Which version of MarkLogic are you using?
10.0-3
Which version of the Data Hub are you using?
5.2

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  `java -jar envision.jar -d > myoutput.txt`

**Comment by xmlnovelist** [comment]
@wpaven I believe this should be reclassified a bug. Two way relationships can be created in Connect and viewed in Know, but they're not viewable in Explore. Explore users need an accurate view of the model, otherwise the usefulness of Explore in architect-business modeling conversations is compromised.

**Comment by wpaven** [comment]
1.0.5
