### ISSUE TITLE
[BUG] saving entities break when nesting too many relationships

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/envision#70]
If there are multiple nested relationships then entity creation fails.

![image](https://user-images.githubusercontent.com/630382/85143755-23ee4b00-b218-11ea-836c-76a7310271bc.png)

**Comment by wpaven** [comment]
is it nested relationships? or nested entities?  i believe dhf by default sets entities as nested, but we don't necessarily want that. we may want to be more explicit.
