### ISSUE TITLE
[FEATURE] Automagic Notifications 

### ISSUE THREAD

**Issue by wpaven** [marklogic-community/envision#83]
**Is your feature request related to a problem? Please describe.**

Currently, running a match step with action of notify, the step will run, but you have to refresh envision to have the alert bubble show up in the right with the user name that notifies users of potential merges in inbox.  Can we automagically have this display without having to refresh the page?

**What is the user-facing scenario that prompted this gap in functionality?**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by paxtonhare** [comment]
I'm adding code to handle this. It will only work when the flows are run from envision. It cannot detect and update the notification when flows are run externally (gradle quickstart) as that would require polling the database

**Comment by paxtonhare** [comment]
fixed in develop
