### ISSUE TITLE
[FEATURE] export to csv / BI Tool

### ISSUE THREAD

**Issue by wpaven** [marklogic-community/envision#96]
**Is your feature request related to a problem? Please describe.**

**What is the user-facing scenario that prompted this gap in functionality?**

Once I've harmonized data, want the ability to export csv(s) for BI Tool. And/or provide URL that BI tool can read data using web connection.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by paxtonhare** [comment]
fixed in develop. pending next release
