### ISSUE TITLE
[BUG]  Compatibility to MarkLogic 9

### ISSUE THREAD

**Issue by bgeorge111** [marklogic-community/envision#98]
*### Welcome Envision enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem: When MarkLogic version 9.x is used, some of the envision modules do not work properly because of the spread operator usage. Example. findEntities.sjs
Instead of spread operator, Object.assign might be a good alternative so that it would work in ML9 and ML10. I am not sure what in the JS engine is making it incompatible. But, I know that JS engine version is different in ML9 and ML10. 

What behavior are you expecting?
Compatibility with ML9 which is an actively supported version

What are the steps to reproduce the issue:
Run the HR360 usecase. Exploring FINAL DB does not work. The error is
Local message: failed to POST at /envision/search/findEntities.sjs: Internal Server Error. Server Message: JS-JAVASCRIPT: ...result, -- Error running JavaScript request: SyntaxError: Unexpected token ... . See 

#### Tech details

Which Operating System are you using? Windows

Which version of MarkLogic are you using? ML9, ML10

Which version of the Data Hub are you using? 5.2.3

**Comment by wpaven** [comment]
MarkLogic 9 is EOL June 2021.  
Envision has always required MarkLogic 10 or greater.
